Running on cn8.hpc.itu.dk:
Currently processing dataset Hi-Small
Traceback (most recent call last):
  File "/home/adgi/FraudGT/banks/bank_analysis.py", line 76, in <module>
    data = pd.read_csv(datasets[dataset])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../Data/HI-Small_Trans.csv'
